### ISSUE TITLE
请教下 你们集成到线上版本了没

### ISSUE THREAD

**Issue by ganvinalix** [wuyunfeng/BMANRDector#1]
请教下 你们集成到线上版本了没？这个打印函数确实很要性能，甚至联系多次打印堆栈信息如500次还有可能会crash

**Comment by wuyunfeng** [comment]
你遇到了什么问题？连续打印调用栈是有可能崩溃的，因为在iOS下打印线程调用栈本身是一件不是十分安全的事，因为会暂停所有线程，遍历线程的栈帧。在线上版本不建议使用。

**Comment by wuyunfeng** [comment]
你遇到了什么问题，详细描述下我看看能不能给你优化下？连续打印调用栈是有可能崩溃的，因为在iOS下打印线程调用栈本身是一件不是十分安全的事，因为会暂停所有线程，遍历线程的栈帧。在线上版本不建议使用。没有集成到线上，线下调试使用，调试时不加断点，因为select线程不受runloop控制，断点时，受bsd内核控制唤醒时间。
